### ISSUE TITLE
Store table ids in local file and only get new when "something went wrong" or there is none

### ISSUE THREAD

**Issue by kristofferremback** [Kugghuset/apicBI#16]
I believe we might prefer not constantly asking for the ID when making requests, as they shouldn't really change all that often. When/if they'd change we would catch that, fetch and store the new ones, and retry the request until success.

**Comment by Hybron** [comment]
We could save the ID (like we're saving the AZURE token and lastUpdate) and if a request fails over not finding the dataset. We will use powerBi.datasetExists('ApicBI') to fetch a new DatasetId.
